# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tilt-gateway.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tilt-gateway.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x12tilt-gateway.proto\"\xe3\x01\n\x07tiltmsg\x12$\n\x06\x63olour\x18\x01 \x01(\x0e\x32\x14.tiltmsg.colour_type\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x12\x17\n\x0fspecificGravity\x18\x03 \x01(\x02\x12\x11\n\ttimeStamp\x18\x04 \x01(\x05\"q\n\x0b\x63olour_type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x07\n\x03RED\x10\x01\x12\t\n\x05GREEN\x10\x02\x12\t\n\x05\x42LACK\x10\x03\x12\n\n\x06PURPLE\x10\x04\x12\n\n\x06ORANGE\x10\x05\x12\x08\n\x04\x42LUE\x10\x06\x12\n\n\x06YELLOW\x10\x07\x12\x08\n\x04PINK\x10\x08\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_TILTMSG_COLOUR_TYPE = _descriptor.EnumDescriptor(
  name='colour_type',
  full_name='tiltmsg.colour_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GREEN', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLACK', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PURPLE', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORANGE', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLUE', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='YELLOW', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PINK', index=8, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=137,
  serialized_end=250,
)
_sym_db.RegisterEnumDescriptor(_TILTMSG_COLOUR_TYPE)


_TILTMSG = _descriptor.Descriptor(
  name='tiltmsg',
  full_name='tiltmsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='colour', full_name='tiltmsg.colour', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='tiltmsg.temperature', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='specificGravity', full_name='tiltmsg.specificGravity', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='tiltmsg.timeStamp', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TILTMSG_COLOUR_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=250,
)

_TILTMSG.fields_by_name['colour'].enum_type = _TILTMSG_COLOUR_TYPE
_TILTMSG_COLOUR_TYPE.containing_type = _TILTMSG
DESCRIPTOR.message_types_by_name['tiltmsg'] = _TILTMSG

tiltmsg = _reflection.GeneratedProtocolMessageType('tiltmsg', (_message.Message,), dict(
  DESCRIPTOR = _TILTMSG,
  __module__ = 'tilt_gateway_pb2'
  # @@protoc_insertion_point(class_scope:tiltmsg)
  ))
_sym_db.RegisterMessage(tiltmsg)


# @@protoc_insertion_point(module_scope)
